"""
Find the Difference: From Leet code
You are given two strings s and t. String t is generated by random shuffling string s and then add one more letter at a random position. Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"
"""
def findTheDifference(self, s: str, t: str) -> str:
    result = 0
    for char in t:
        result += ord(char)

    for char in s:
        result -= ord(char)

    return chr(result)
    # Below is my code using dictionary
    # item = {}
    # for value in s:
    #     if item.get(value):
    #         item[value] += 1
    #     else:
    #         item[value] = 1

    # for value in t:
    #     if item.get(value):
    #         item[value] -= 1
    #     else:
    #         item[value] = 1

    # for key, value in item.items():
    #     if value == 1:
    #         return key
